export interface Vehicle {
  id: string;               // Supabase UUID
  user_id: string;          // Owner of the vehicle
  make: string;             // Required
  model: string;            // Required
  year: number;             // Required
  vin?: string;             // Optional
  license_plate?: string;   // Optional
  color?: string;           // Optional
  mileage?: number;         // Optional
  engine?: string;          // Optional, e.g., "2.0L 4-Cylinder"
  image_url?: string;       // Optional, for uploaded picture
  created_at: string;       // Auto-generated by Supabase
  notes?: string;           // Optional
}
