export interface Vehicle {
  id: string;               // Supabase UUID
  user_id: string;          // Owner of the vehicle
  make: string;             // Required
  model: string;            // Required
  year: number;             // Required
  vin?: string;             // Optional
  license_plate?: string;   // Optional
  color?: string;           // Optional
  mileage?: number;         // Optional
  engine?: string;          // Optional, e.g., "2.0L 4-Cylinder"
  image_url?: string;       // Deprecated: use images array instead (kept for backward compatibility)
  images?: string[];        // Optional, array of image URLs

  // Extended vehicle details
  drive_type?: string;      // Optional, e.g., "2WD", "4WD", "AWD", "RWD"
  tire_size?: string;       // Optional, e.g., "225/65R17"
  trim?: string;            // Optional, e.g., "LT", "Sport", "Limited"
  body_type?: string;       // Optional, e.g., "Sedan", "SUV", "Truck"
  transmission?: string;    // Optional, e.g., "Automatic", "Manual", "CVT"
  fuel_type?: string;       // Optional, e.g., "Gasoline", "Diesel", "Electric", "Hybrid"

  // Optional equipment (stored as JSON array)
  optional_equipment?: string[];  // Optional, e.g., ["Leather Seats", "Sunroof", "Navigation"]

  // Purchase information
  purchase_date?: string;   // Optional, ISO date string
  purchase_price?: number;  // Optional, purchase price in dollars
  warranty_expiration?: string; // Optional, ISO date string

  // Vehicle status
  status?: 'Active' | 'Inactive' | 'Sold' | 'Stored' | 'In Repair'; // Default: 'Active'

  // Vehicle type/category
  vehicle_type?: 'Car' | 'Truck' | 'SUV' | 'Van' | 'Motorcycle' | 'ATV' | 'UTV' | 'Trailer' | 'Tractor' | 'Other'; // Type of vehicle/equipment
  custom_type?: string;     // Custom type when "Other" is selected

  created_at: string;       // Auto-generated by Supabase
  notes?: string;           // Optional
}

// Vehicle status options
export const VEHICLE_STATUSES = ['Active', 'Inactive', 'Sold', 'Stored', 'In Repair'] as const;

// Vehicle type options
export const VEHICLE_TYPES = ['Car', 'Truck', 'SUV', 'Van', 'Motorcycle', 'ATV', 'UTV', 'Trailer', 'Tractor', 'Other'] as const;
